# Generated by Django 3.2.25 on 2026-06-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0002_grado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
    ]
