# Generated by Django 3.2.25 on 2026-06-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0004_tema'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
