# Generated by Django 3.2.25 on 2026-07-23 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0005_tema_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Palabra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra_espanol', models.CharField(max_length=100)),
                ('traduccion', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='palabras/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audios/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.categoria')),
            ],
        ),
        migrations.RemoveField(
            model_name='tema',
            name='grado',
        ),
        migrations.RemoveField(
            model_name='tema',
            name='idioma',
        ),
        migrations.RemoveField(
            model_name='tema',
            name='materia',
        ),
        migrations.AddField(
            model_name='idioma',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Grado',
        ),
        migrations.DeleteModel(
            name='Materia',
        ),
        migrations.DeleteModel(
            name='Tema',
        ),
        migrations.AddField(
            model_name='palabra',
            name='idioma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.idioma'),
        ),
    ]
